SELECT SIGN(TP.PROFIT) AS SIGN,
	SIGN(TP.PROFIT) * SUM(ST."dealFunds"::DECIMAL / ST."dealSize"::DECIMAL - BT."dealFunds"::DECIMAL / BT."dealSize"::DECIMAL) AMT
FROM TRADE_PAIRS TP
JOIN TRADES BT ON TP.BUY_ID = BT.ID
JOIN TRADES ST ON TP.SELL_ID = ST.ID
WHERE BT."createdAt"::DECIMAL >= {timestamp}
GROUP BY SIGN(TP.PROFIT)