WITH TT AS
	(SELECT KUCOIN_NAME
		FROM COINS
		WHERE ALLOW_TRADE = 1)
SELECT KUCOIN_NAME,
	SUM(CASE WHEN T.ID IS NULL
			THEN 0
			ELSE 1
		END) AS COUNT_OF_TRADES,
	SUM(COALESCE(T.PROFIT, 0)) AS SUM_PROFIT
FROM TT C
LEFT JOIN
	(SELECT T.SYMBOL,
			T.ID,
			TD.PROFIT,
			T."createdAt"
		FROM TRADES T
		JOIN TRADE_PAIRS TD ON T.ID = TD.BUY_ID) T ON T.SYMBOL = C.KUCOIN_NAME
AND T."createdAt" > {timestamp}
GROUP BY KUCOIN_NAME
ORDER BY COUNT_OF_TRADES DESC